name: zoomdrive
description: GitHub action to download Zoom recordings periodically and upload to Google Drive
author: 'Open Healthcare Network'
branding:
  icon: 'refresh-cw'
  color: 'green'

inputs:
  zoom_account_id:
    description: Zoom Account ID
    required: true

  zoom_client_id:
    description: Client ID of Zoom OAuth App
    required: true

  zoom_client_secret:
    description: Client Secret of Zoom OAuth App
    required: true

  lookback_days:
    description: Number of days to keep Zoom meeting recordings
    required: false
    default: '30'

  end_date:
    description: End date of Zoom meeting recordings to keep
    required: false

  delete_on_success:
    description: Delete Zoom Meeting Recording files after uploading to Google Drive
    required: false
    default: 'false'

  gsa_credentials:
    description: Google Service Account Credentials
    required: true

  meeting_gdrive_folder_map:
    description: Base64 encoded JSON Map of meeting ID to folder ID
    required: true

outputs:
  result:
    description: The result of the action

runs:
  using: node16
  main: dist/index.js
  post: cleanup.js
